---
title: "Solving equations"
teaching: 0
exercises: 0
questions:
  - "Key question (FIXME)"
objectives:
  - "First learning objective. (FIXME)"
keypoints:
  - "First key point. Brief Answer to questions. (FIXME)"
---




library(devtools)
devtools::install_github("dirkschumacher/ompr.highs")
install.packages("highs")
install.packages("ompr.roi")


Hvordan løser vi algebraiske ligningssystemer?

Uden at skrive noget selv der optimerer.

Et eksempel:

Minimer $x_0 + x_1 + 3$

givet at:

$x_1 \leq 7$

$5 \leq x_0 + 2x_1 \leq 15$

$6 \leq 3x_0 + 2x_1$

$0 \leq x_0 \leq 4$

$1 \leq x_1$

Det er der en pakke der kan. 





library(highs)
library(ompr)
library(ompr.highs)
library(dplyr)


Bemærk at ompr.highs skal installeres fra github:


devtools::install_github("dirkschumacher/ompr.highs")




Så bygger vi modellen. Først initialiserer vi modellen:

model <- MIPModel()


Så tilføjer vi variable:

model <- model %>% 
      add_variable(x0, lb = 0, ub = 4, type = "continuous") %>%
      add_variable(x1, lb = 1, type = "continuous")


$x_0$ har lower bound (lb) lig 0, og upper bound (ub) lig 4. Og det er en 
kontinuer variabel.

$x_1$ har lower bound 1, og er kontinuer.

så tilføjer vi de øvrige begrænsninger:



model <- model %>% 
      add_constraint(x1 <= 7) %>%
      add_constraint(x0 + 2*x1 <= 15) %>%
      add_constraint(x0 + 2*x1 >= 5) %>%
      add_constraint(3*x0 + 2*x1 >= 6)


Og endelig angiver vi hvad målet er. $x_0 + x_3 + 3$ skal minimeres:

model <- model %>% 
  set_objective(x0+x1+3, sense = "min") 


Så er vi klar til at løse modellen:
  

# solve model
solution <- model %>% 
  solve_model(highs_optimizer())


Og når den er færdig, kan vi kigge på resultatet.

Vi fandt en optimal løsning:

solution$status


Værdien, minimum af vores mål, er:

solution$objective_value


Og selve løsningen er givet ved:

solution$solution


{% include links.md %}