---
title: "Colorblindness"
teaching: 0
exercises: 0
---

:::::::::::::::::::::::::::::::::::::: questions 

- Which color should I chose in my visualisations to accomodate colorblind people?
- Why should I accomodate colorblind people?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Gain an understanding of the pros and cons of chosing colorblind-friendly colors

::::::::::::::::::::::::::::::::::::::::::::::::

Not everyone experiences colors in the same way. Stereotypical memes about women seeing six different colors where
men only see one (violet) not withstanding, the way colors are experienced depends on culture, context, the
quality of the screen we are viewing them on, the specific type of printer we print them on, the lighting. And biology.

Up to about 8% of men, and 0.5% of women have some sort of color blindness. Depending on genetic descent these 
numbers varies, and to complicate matters further, different types of colorblindness exists. A selection is 
shown below:

* Tritanomaly: Blue-yellow colorblindness. Affects < 0.01%, both men and women.
* Deutoanomaly: Red-green colorblindness. Affects ~6% of all men.
* Protanomaly: Red-green colorblindness. Affects ~2% of all men.
* Desaturated attempts to simulate complete colorblindness (akromatopsi). This affects ~0.003% 



### Do we need to take colorblindness into account?

Yes. And no.

There are things that are almost impossible to visualise in palettes that 
accomodate the different kinds of color blindness. And are completely 
impossible if they have to accomodate _all_ the different kinds.

Some plots have a primary purpose of being spectacular and visually stunning.
That can also be extremely difficult if we limit the colors we have to work with.

But. If the purpose of the plot is to convey information about data, rather than
being art, it is a good idea to take colorblindness into consideration. 
Not only to help color blind people, but also because it makes it easier for people
with normal color vision to spot differences and understand our visusalisations. 




## Farveblindhed

Det er ofte en god ide at tjekke hvordan ens palette bliver opfattet af farveblinde.

Pakken colorblindr giver et bud på det. Den skal installeres fra github:

```{r}
library(colorblindr)
```






cvd_grid vil vise os bruger som udgangspunkt det sidste plot vi lavede.

palette_plot(wesanderson::wes_palettes$FantasticFox1)
cvd_grid()


Og det var ethvert plot:


ggplot(mtcars, aes(cyl, mpg, colour = gear)) + 
  geom_point()

cvd_grid()


Det en person med normalt farvesyn får her, er et estimat af hvordan et plot vil se ud ved forskellige typer af farveblindhed. Og det er nok blot et estimat, men bedre end ingenting.


## Hvordan bruger vi så en palette i et plot?

Vi tilføjer en linie til vores plot `scale_fill_manual` eksempelvis:


mtcars %>% 
  ggplot(aes(hp, fill = factor(am))) +
  geom_histogram(position = "dodge") +
  scale_fill_manual(values=wesanderson::wes_palettes$FantasticFox1)
  

scale_c


## rcolorbrewer
Der bør også være noget om rcolorbrewer


::::::::::::::::::::::::::::::::::::: keypoints 

- First key point. Brief Answer to questions. (FIXME)

::::::::::::::::::::::::::::::::::::::::::::::::