---
title: 'Fences på vores undervisningssider'
teaching: 10
exercises: 2
---

:::::::::::::::::::::::::::::::::::::: questions 

- Hvilke fences understøtter vores Workbench-opsætning?
- Hvordan indlejres challenges, hints og solutions korrekt?
- Hvilken fence passer til hvilken undervisningsfunktion?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Oprette og afslutte en fence med korrekt syntaks.
- Vælge en fence ud fra indholdets undervisningsmæssige funktion.
- Indlejre hint og solution korrekt i en challenge.
- Oprette synkroniserede faner med group-tab.
- Kontrollere resultatet ved at bygge lektionen lokalt.

::::::::::::::::::::::::::::::::::::::::::::::::


Fences. Det vi bruger til at indsætte de små (eller ikke så små) farvede blokke
på siderne. De starter alle med mindst fire ":" og derefter ordet; eksempelvis
"callout". Og når man er færdig med indholdet, skal der være mindst fire ":" igen.

Hvad er ordet så? Ordet er altid det der står på position X i:
"dette er en X fence".



:::: callout
## dette er en callout fence


::::

:::: prereq
## dette er en prereq fence


::::


:::: checklist
## dette er en checklist fence

::::


Bemærk at hint-fencen mangler en ikon til venstre.

:::: hint
## dette er en hint fence

::::


:::: discussion
## dette er en discussion fence

::::


:::: testimonial
## dette er en testimonial fence

::::

:::: instructor
## dette er en instructor fence

::::

:::: caution
## Dette er en caution fence

Bemærk at sandpaper vil insistere på ikke at kende til denne fence. Men
den fungerer altså fint alligevel, så det er fejl under bygningen af siden
man roligt kan ignorere.

::::

:::: spoiler
## dette er en spoiler fence

::::


:::: challenge
## dette er en challenge fence

:::: solution
## Den optræder som regel med en solution fence

Og den er "inde i" challenge fencen.


::::


::::


## Fanegruppe Eksempel

Vi starter med en group-tab fence, og så har vi nogen overskrifter til de
forskellige tabs, og deres indhold. Vær opmærksom på at når man skifter til 
eksempelvis "Mac" i en group-tab, så skifter de andre group-tabs også til
"Mac".

::: group-tab

### Windows

1

### Mac

2

### Linux

3

:::

::: group-tab

### Windows

4

### Mac

5

### Linux

6

### raspbian

7

:::


## livelink


Kan pt installeres fra. Men fungerer ikke her af årsager. Når pakken er tilgængelig på cran er den værd at kigge på.

"coatless-rpkg/livelink"



```{r load_library}
library(tidyverse)
```

## Tabeller

Der er ikke en direkte måde at justere bredde af tabeller. Men antallet af "-" i linie to har betydning for hvordan pandoc vælger bredden.

::::::::::::::::::::::::::::::::::::: keypoints 

- Fences giver indholdet semantisk struktur og ikke kun en bestemt farve.
- Indlejrede fences skal lukkes i omvendt rækkefølge af den, de blev åbnet i.
- solution og hint hører normalt til en konkret challenge.
- Instructor-noter kan vises for undervisere uden at fylde i kursistvisningen.
- Komponenter, som Workbench ikke officielt understøtter, bør testes før de bruges i kursusmateriale.

::::::::::::::::::::::::::::::::::::::::::::::::


